spring:
  datasource:
    url: "jdbc:mysql://localhost/zippyziggy"
    username: "root"
    password: "kim8383!"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: XUKemfiZfrEWLtykdkjfeliwjfd59YLt5XXXkAdqZu33
