spring:
  datasource:
    url: "jdbc:mysql://zippyziggydb.cylq2wgsymni.us-east-1.rds.amazonaws.com:3306/zippyziggydb"
    username: "admin"
    password: "chlskfo18*"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: XUKemfiZfrEWLtykdkjfeliwjfd59YLt5XXXkAdqZu33

server:
  port: 8080
  address: 0.0.0.0

chatbot:
  api:
    url: http://52.79.156.162:8000/chat